Webshop/Models/User.cs
using System;

namespace ASPWebshop.Pages.Models
{
    public class User
    {
        public Guid ID { get; set; }
        public string Username { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
    }
}

Webshop/Models/UserLoginResult.cs
using ASPWebshop.Common.Models;

namespace ASPWebshop.Pages.Models
{
    public class UserLoginResult
    {
        public WebshopUser WebshopUser { get; set; }
        public bool Verified { get; set; }
    }
}

Webshop/Models/WebshopUser.cs
using System;

namespace ASPWebshop.Pages.Models
{
    public class WebshopUser
    {
        public Guid ID { get; set; }
        public string Username { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
    }
}

Webshop/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPWebshop.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public ErrorModel()
        {
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Webshop/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPWebshop.Pages
{
    public class IndexModel : PageModel
    {

        public IndexModel()
        {
        }

    }
}

Webshop/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using ASPWebshop.Pages.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ASPWebshop.Services.Interfaces;
using ASPWebshop.Exceptions;
using ASPWebshop.Common.Models;

namespace ASPWebshop.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;
        private readonly ILoginService _loginService;

        public string ErrorMessage { get; set; }

        public LoginModel(ILogger<PrivacyModel> logger, ILoginService loginService)
        {
            _logger = logger;
            _loginService = loginService;

        }

        [BindProperty]
        public LoginViewModel LoginViewModel { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            { 
                if (this.User.Identity.IsAuthenticated)
                {  
                    await SignOutAsync();
                    return this.RedirectToPage("Index");
                }
            }
            catch (Exception ex)
            {
                Console.Write(ex);
            }

            return this.Page();
        }

        public async Task<IActionResult> LogOff()
        {
            await SignOutAsync();
            return this.RedirectToPage("Index");
        }

        public async Task<IActionResult> OnPostLogIn()
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var username = this.LoginViewModel.Username;
                    var password = this.LoginViewModel.Password;
                    var userResult = _loginService.VerifyUser(username, password);
                    if (userResult.Verified)
                    {
                        await this.SignInUser(userResult.WebshopUser);

                        return this.RedirectToPage("Index");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Invalid username or password.");
                    }
                }
            }
            catch (UserException ex)
            {
                ErrorMessage = ex.Message;
            } catch (Exception e) {
                Console.Write(e);
            }
            return this.Page();
        }


        private async Task SignOutAsync()
        {
            var authenticationManager = Request.HttpContext;
            await authenticationManager.SignOutAsync();
        }

        private async Task SignInUser(WebshopUser user)
        {
            // Initialization.  
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.Username),
                new Claim(ClaimTypes.Email, user.EMail),
                new Claim(ClaimTypes.UserData, user.ID.ToString()),
                new Claim(ClaimTypes.Role, "Administrator")
            };

            try
            {
                var claimIdenties = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties
                {
                    //AllowRefresh = <bool>,
                    // Refreshing the authentication session should be allowed.

                    //ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(10),
                    // The time at which the authentication ticket expires. A 
                    // value set here overrides the ExpireTimeSpan option of 
                    // CookieAuthenticationOptions set with AddCookie.

                    IsPersistent = true,
                    // Whether the authentication session is persisted across 
                    // multiple requests. When used with cookies, controls
                    // whether the cookie's lifetime is absolute (matching the
                    // lifetime of the authentication ticket) or session-based.

                    //IssuedUtc = <DateTimeOffset>,
                    // The time at which the authentication ticket was issued.

                    //RedirectUri = <string>
                    // The full path or absolute URI to be used as an http 
                    // redirect response value.
                };
                var claimPrincipal = new ClaimsPrincipal(claimIdenties);
                var authenticationManager = Request.HttpContext;

                // Sign In.  
                await authenticationManager.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal, authProperties);
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message);
            }
        }
    }
}

Webshop/Pages/Privacy.cshtml.cs
using ASPWebshopDatabase.Services;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ASPWebshop.Pages
{
    public class PrivacyModel : PageModel
    {
        public PrivacyModel()
        {}
    }
}

Webshop/Pages/UserPage.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;
using ASPWebshop.Services.Interfaces;
using ASPWebshop.Common.Models;
using ASPWebshopDatabase.Services;

namespace ASPWebshop.Pages
{
    public class UserPageModel : PageModel
    {
        private readonly IUserDataAccess _userDataAccess;

        public WebshopUser WebshopUser { get; set; }

        public UserPageModel(IUserDataAccess userDataAccess)
        {
            _userDataAccess = userDataAccess;
        }

        public void OnGet()
        {
            var identity = User.Identity as ClaimsIdentity;
            IEnumerable<Claim> claims = identity.Claims;
            var claim = claims.First(x => x.Type.Equals(ClaimTypes.Name));
            WebshopUser = _userDataAccess.GetUser(claim.Value);
        }
    }
}

Webshop/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Bitch</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <h2>The time on the server is @DateTime.Now</h2>
</div>

@if (Model.User.Identity.IsAuthenticated) {
    <h1>Hello, @Model.User.Identity.Name!</h1>
    <p>You can only see this content if you're authenticated.</p>
} else {
    <h1>Authentication Failure!</h1>
    <p>You're not signed in.</p>
}

Webshop/Pages/Login.cshtml
@page
@model LoginModel
@{
    ViewData["Title"] = "Login";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to login to your site.</p>


@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <p style="color: red;">@Model.ErrorMessage</p>
}

<section>
    <form method="post" role="form" class="form-horizontal">
        @Html.AntiForgeryToken()

        <h4>Use a local account to log in.</h4>
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(m => m.LoginViewModel.Username, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.LoginViewModel.Username, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LoginViewModel.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.LoginViewModel.Password, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.LoginViewModel.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.LoginViewModel.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <label asp-for="LoginModel.Username" class = "col-md-2 control-label"></label>
            <div class="col-md-10">
            <input asp-for="LoginModel.Username" class="form-control" />
            <span class="alert-danger" asp-validation-for="LoginModel.Username"></span>
            </div>
            </div>

            <div class="form-group">
            <label asp-for="LoginModel.Password" class="col-md-2 control-label"></label>
            <div class="col-md-10">
            <input asp-for="LoginModel.Password" class="form-control" />
            <span class="alert-danger" asp-validation-for="LoginModel.Password"></span>
            </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button asp-page-handler="LogIn" class="btn btn-default">Log in</button>
            </div>
        </div>
    </form>
</section>

Webshop/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPWebshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ASPWebshop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        @if (Model.User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/UserPage">User</a>
                            </li>
                        }
                        <li class="nav-item">
                            @if (Model.User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-area="" asp-page="/Login">Log out</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-page="/Login">Login</a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASPWebshop - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Webshop/Pages/UserPage.cshtml
@page
@model UserPageModel
@{
    ViewData["Title"] = "User Profile";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your user information</p>

<p>Username: @Model.WebshopUser.Username!</p>
<p>EMail: @Model.WebshopUser.EMail!</p>